sed -i '' '/CURRENT_PROJECT_VERSION: 1/a\
      CODE_SIGN_STYLE: "Manual"\
      CODE_SIGN_IDENTITY: "$(APPLE_CERTIFICATE_SIGNING_IDENTITY)"\
      PROVISIONING_PROFILE_SPECIFIER: "$(APPLE_PROV_PROFILE_UUID)"\
' project.yml
